site_name: "DeepDenoiser"
site_description: 'DeepDenoiser: Seismic Signal Denoising and Decomposition Using Deep Neural Networks'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'wayneweiqiang/DeepDenoiser'
repo_url: 'https://github.com/wayneweiqiang/DeepDenoiser'
nav:
    - Overview: README.md
    - Interactive Example: example_interactive.ipynb
    - Batch Prediction: example_batch_prediction.ipynb
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter